services:
  # Удалите или закомментируйте этот блок, если не используете локальную БД
  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: RecipeDB
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 1234
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - my_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d0hfd0a4d50c73bgkbo0-a.oregon-postgres.render.com/reipce_db
      SPRING_DATASOURCE_USERNAME: altory
      SPRING_DATASOURCE_PASSWORD: LYmK3QxzLF7kmf4HlbiDuXOW8a4kZgn6
    ports:
      - "8080:8080"
    networks:
      - my_network

  frontend:
    build:
      context: ./recipe-service
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - my_network

networks:
  my_network: